  <div class="login">
	
		<form action="my.local.com/user/login" method="post">
            <label for="login-field">Логин:</label>
            <input type="text" name="login" id="login-field" maxlength="6" size="10">
           
            <label for="password-field">Пароль:</label>
            <input type="password" name="password" id="password-field" size="10">
		<input type="submit" name="vhod" value="Войти">
	    
		</form>	
	  
	  <form action="my.local.com/user/registration" method="post">
		<button  type="submit" name="registr">Зарегистрироваться</button>
			</form>	
</div>