<div id="footer">

		<div class="footer-left">
	Хочу участвовать в проекте<br/>
		Как поддержать проект?
	</div>
 
		
	
	<div  class="footer-center">
		
		<article>
 	
		 <a>&copy; Проба сайта</a> <br/> 
		<time>17.02.2018</time> Начал делаться сайт <a href="/">my.local.com</a> 
	
  </article> 
	</div>

<div class="footer-right">
		<a href="/about"><b>О нас</b></a>
	
			<div>
		<a>	&#9742;+380000000000</a>
		</div>
	</div>	
	
</div>
 

  
