<div class="header">
    <div class="logo header-left"><a href="/" ><img width="100%" src="/mylocal.png" title="my.local.com"> </a></div>
    {{$headerMenu}}
    <div class="header-right">	<img width="300" src="/namesite.png"></div>
	<div class="logo header-left"><a href="/" ><img width="100%" src="/mylocal.png" title="my.local.com"> </a></div>

	<div class="menu header-center">
	<ul id="navbar">
    <li>
        <a href="/index">Главная</a>
		<ul id="navbar1">
            <li><a href="/tree/why">Как это сделать</a></li>
            <li><a href="/tree/hard">Немного сложно</a></li>
        </ul>
    </li>
    <li>
        <a href="/about">О нас</a>
    </li>
    <li>
        <a href="/tree">Каталог</a>
        <ul id="navbar1">
            <li><a href="/tree/view">Каталог смотреть</a></li>
            <li><a href="/tree/add">Добавить в каталог</a></li>
        </ul>
    </li>
</ul>
</div>
	
	<div class="header-right">	<img width="300" src="/namesite.png"></div>
</div>
