<html doctype="html">
    <head>
        <title>{{$title}}</title>
        <meta name="title" content="{{$title}}" charset="UTF-8"/>
        {{$headfiles}}
    </head>
    <body>
        {{$header}}
        {{$menu}}
        <!-- контент сюда попадает из файла , которий засетан в текущем контролере - например $template->setFile('templates/main.phtml') -->
       <div class="content"> {{$content}} </div>
		 {{$pager}}
        {{$footer}}
    </body>
</html>