<div class="menu">
	<ul id="navbar">
    <li>
        <a href="/index">Главная</a>
    </li>
    <li>
        <a href="/about">О нас</a>
    </li>
    <li>
        <a href="/tree">Каталог</a>
        <ul id="navbar1">
            <li><a href="/tree/view">Каталог смотреть</a></li>
            <li><a href="/tree/add">Добавить в каталог</a></li>
        </ul>
    </li>
</ul>
</div>
<br/>
<br/>
<hr/>

