
   <ul class="pager center">
	<li>Нумерация страниц</li> 
    <li class="pager-current first"><span>1</span></li>
    <li class="pager-item"><a href="/node?page=1" title="На страницу номер 2">2</a></li>
    <li class="pager-item"><a href="/node?page=2" title="На страницу номер 3">3</a></li>
    <li class="pager-item"><a href="/node?page=3" title="На страницу номер 4">4</a></li>
    <li class="pager-next last"><a href="/node?page=1" title="На следующую страницу">›</a></li>
   </ul>