<div class="registration">
<form action="/user/registration" method="post">
            <label for="name-field">Имя:</label><br/>
            <input type="text" name="name" id="name-field"><br/><br/>
	
			<label for="surname-field">Фамилия:</label><br/>
            <input type="text" name="surname" id="surname-field"><br/><br/>
	
			<label for="patronymic-field">Отчество:</label><br/>
            <input type="text" name="patronymic" id="patronymic-field"><br/>
	
	<p>Ваш пол:</p>
			<label>
                <input type="radio" name="pol" value="Мужской">
                Мужской
            </label>
			<label>
                <input type="radio" name="pol" value="Женский">
                Женский
            </label>
	
			<p>Дата рождения</p>
			<select name="day">
		  		<option>День</option>
		  		<?php for($i = 01;  $i <= 31; $i++ ): ?>
					<option value="<?php echo $i; ?>"><?php echo $i; ?></option>
				<?php endfor; ?>
			</select>
			
			<select name="month">
		  		<option>Месяц</option>
		  		<?php for($i = 01;  $i <= 12; $i++ ): ?>
					<option value="<?php echo $i; ?>"><?php echo $i; ?></option>
				<?php endfor; ?>
			</select>
	
			<select name="year">
				<option>Год</option>
				<?php for($i = 2018; 1950 <= $i; $i-- ): ?>
					<option value="<?php echo $i; ?>"><?php echo $i; ?></option>
				<?php endfor; ?>
			</select><br/><br/>
	
	 		<label for="email-field">Ваш email:</label><br/>
            <input type="email" name="email" id="email-field"><br/><br/>
	
			<label for="password">Ваш пароль:</label><br/>
            <input type="text" name="password" id="password"><br/><br/>
	
			<input type="submit" name="registration" value="Зарегистрироваться">
	
	
</form>
</div>