
<form action="/user/registration" method="post">
            <label for="name-field">Имя:</label><br/>
            <input type="text" name="name" id="name-field"><br/><br/>
	
			<label for="surname-field">Фамилия:</label><br/>
            <input type="text" name="surname" id="surname-field"><br/><br/>
	
			<label for="patronymic-field">Отчество:</label><br/>
            <input type="text" name="patronymic" id="patronymic-field"><br/>
	
	<p>Ваш пол:</p>
			<label>
                <input type="radio" name="pol" value="Мужской">
                Мужской
            </label>
			<label>
                <input type="radio" name="pol" value="Женский">
                Женский
            </label>
	
			<p>Дата рождения</p>
			<select name="day">
		  		<option value="01">01</option>
		  		<option value="02">02</option>
		  		<option value="03">03</option>
				<option value="04">01</option>
				<option value="05">01</option>
				<option value="06">01</option>
				<option value="07">01</option>
				<option value="08">01</option>
				<option value="09">01</option>
				<option value="10">01</option>
				<option value="11">01</option>
				<option value="12">01</option>
				<option value="13">01</option>
				<option value="14">01</option>
				<option value="15">01</option>
				<option value="16">01</option>
				<option value="17">01</option>
				<option value="18">01</option>
				<option value="19">01</option>
				<option value="20">01</option>
				<option value="21">01</option>
				<option value="22">01</option>
				<option value="23">01</option>
				<option value="24">01</option>
				<option value="25">01</option>
				<option value="26">01</option>
				<option value="27">01</option>
				<option value="28">01</option>
				<option value="29">01</option>
				<option value="30">01</option>
				<option value="31">01</option>
			</select>
			
			<select name="month">
		  		<option value="01">01</option>
		  		<option value="02">02</option>
		  		<option value="03">03</option>
				<option value="04">01</option>
				<option value="05">01</option>
				<option value="06">01</option>
				<option value="07">01</option>
				<option value="08">01</option>
				<option value="09">01</option>
				<option value="10">01</option>
				<option value="11">01</option>
				<option value="12">01</option>
			</select><br/>
	
	<input type="date" name="month">
	
	
		

	
	
	</form>