
<?php 
if(isset($_SESSION['error'])): ?>
    <span style="color:red;"><?php echo $_SESSION['error'] ?></span> 
<?php 
unset($_SESSION['error']);
endif; ?>
<div class="registration">
<form action="/user/registrationPost" method="post">
            <label for="name">Имя:</label><br/>
            <input type="text" name="name" id="name"><br/><br/>
	
			<label for="surname">Фамилия:</label><br/>
            <input type="text" name="surname" id="surname"><br/><br/>
	
			<label for="patronymic">Отчество:</label><br/>
            <input type="text" name="patronymic" id="patronymic"><br/>
	
	<p>Ваш пол:</p>
			<label>
                <input type="radio" name="pol" value="1">
                Мужской
            </label>
			<label>
                <input type="radio" name="pol" value="0">
                Женский
            </label>
	
			<p>Дата рождения</p>
			<select name="day">
		  		<option>День</option>
		  		<?php for($i = 01;  $i <= 31; $i++ ): ?>
					<option value="<?php echo $i; ?>"><?php echo $i; ?></option>
				<?php endfor; ?>
			</select>
			
			<select name="month">
		  		<option>Месяц</option>
		  		<?php for($i = 01;  $i <= 12; $i++ ): ?>
					<option value="<?php echo $i; ?>"><?php echo $i; ?></option>
				<?php endfor; ?>
			</select>
	
			<select name="year">
				<option>Год</option>
				<?php for($i = 2018; 1950 <= $i; $i-- ): ?>
					<option value="<?php echo $i; ?>"><?php echo $i; ?></option>
				<?php endfor; ?>
			</select><br/><br/>
	
	 		<label for="email">Ваш email:</label><br/>
            <input type="email" name="email" id="email"><br/><br/>
	
			<label for="password">Ваш пароль:</label><br/>
            <input type="password" name="password" id="password"><br/><br/>
            
            <label for="password">Подтверждение пароля:</label><br/>
            <input type="password" name="password-confirm" id="password-confirm"><br/><br/>
	
			<input type="submit" name="enter" value="Зарегистрироваться">
	
	
</form>
</div>